import { PublicKey } from '@solana/web3.js';


export const SurveyData = [
    {
        id: 1,
        title: " Ellipsis for Multiple Lines (Optional)  Ellipsis for Multiple Lines (Optional)1",
        reward: 10,
        duration: "2 days",
        limit: 100,
        participants: 50,
        status: "Active",
        owner_name: "John Doe",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",

    },
    {
        id: 2,
        title: " Ellipsis for Multiple Lines (Optional) 2",
        reward: 20,
        duration: "3 days",
        limit: 100,
        participants: 50,
        status: "Active",
        owner_name: "John Doe",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 3,
        title: " Ellipsis for Multiple Lines (Optional) 3",
        reward: 15,
        duration: "1 day",
        limit: 100,
        participants: 50,
        status: "Active",
        owner_name: "John Doe",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 4,
        title: "Survey 4",
        reward: 25,
        duration: "4 days",
        limit: 200,
        participants: 100,
        status: "Active",
        owner_name: "Jane Smith",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",    },
    {
        id: 5,
        title: "Survey 5",
        reward: 30,
        duration: "5 days",
        limit: 150,
        participants: 75,
        status: "inactive",
        owner_name: "Alice Johnson",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",    },
    {
        id: 6,
        title: "Survey 6",
        reward: 12,
        duration: "2 days",
        limit: 120,
        participants: 60,
        status: "active",
        owner_name: "Bob Brown",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 7,
        title: "Survey 7",
        reward: 18,
        duration: "3 days",
        limit: 130,
        participants: 65,
        status: "active",
        owner_name: "Charlie Davis",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 8,
        title: "Survey 8",
        reward: 22,
        duration: "4 days",
        limit: 140,
        participants: 70,
        status: "inactive",
        owner_name: "Diana Evans",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 9,
        title: "Survey 9",
        reward: 35,
        duration: "6 days",
        limit: 160,
        participants: 80,
        status: "active",
        owner_name: "Ethan Foster",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 10,
        title: "Survey 10",
        reward: 40,
        duration: "7 days",
        limit: 170,
        participants: 85,
        status: "active",
        owner_name: "Fiona Green",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 11,
        title: "Survey 11",
        reward: 28,
        duration: "5 days",
        limit: 180,
        participants: 90,
        status: "inactive",
        owner_name: "George Harris",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 12,
        title: "Survey 12",
        reward: 50,
        duration: "8 days",
        limit: 190,
        participants: 95,
        status: "active",
        owner_name: "Hannah Irving",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 13,
        title: "Survey 13",
        reward: 45,
        duration: "6 days",
        limit: 200,
        participants: 100,
        status: "active",
        owner_name: "Ian Jackson",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 14,
        title: "Survey 14",
        reward: 55,
        duration: "9 days",
        limit: 210,
        participants: 105,
        status: "inactive",
        owner_name: "Julia King",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 15,
        title: "Survey 15",
        reward: 60,
        duration: "10 days",
        limit: 220,
        participants: 110,
        status: "active",
        owner_name: "Kevin Lewis",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 16,
        title: "Survey 16",
        reward: 65,
        duration: "11 days",
        limit: 230,
        participants: 115,
        status: "active",
        owner_name: "Laura Martinez",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",    },
    {
        id: 17,
        title: "Survey 17",
        reward: 70,
        duration: "12 days",
        limit: 240,
        participants: 120,
        status: "inactive",
        owner_name: "Michael Nelson",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",    },
    {
        id: 18,
        title: "Survey 18",
        reward: 75,
        duration: "13 days",
        limit: 250,
        participants: 125,
        status: "active",
        owner_name: "Natalie Owens",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",    },
    {
        id: 19,
        title: "Survey 19",
        reward: 80,
        duration: "14 days",
        limit: 260,
        participants: 130,
        status: "active",
        owner_name: "Oliver Parker",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",    },
    {
        id: 20,
        title: "Survey 20",
        reward: 85,
        duration: "15 days",
        limit: 270,
        participants: 135,
        status: "inactive",
        owner_name: "Paula Quinn",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 21,
        title: "Survey 21",
        reward: 90,
        duration: "16 days",
        limit: 280,
        participants: 140,
        status: "active",
        owner_name: "Quincy Roberts",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 22,
        title: "Survey 22",
        reward: 95,
        duration: "17 days",
        limit: 290,
        participants: 145,
        status: "active",
        owner_name: "Rachel Scott",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 23,
        title: "Survey 23",
        reward: 100,
        duration: "18 days",
        limit: 300,
        participants: 150,
        status: "inactive",
        owner_name: "Steven Turner",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",    }
]


export const SellData = [
    {
        survey_id: 1,
        title: "Solana Usage Stats",
        summary: "Detailed statistics on Solana blockchain usage.",
        data_type: "PAID",
        price: 50,
        buyer: null,
        sold_at: 0,
    },
    {
        survey_id: 2,
        title: "User Demographics",
        summary: "Insights into user demographics for surveys.",
        data_type: "FREE",
        price: 0,
        buyer: null,
        sold_at: 0,
    },
    {
        survey_id: 3,
        title: "Survey Completion Rates",
        summary: "Data on survey completion rates across platforms.",
        data_type: "PAID",
        price: 30,
        buyer: null,
        sold_at: 0,
    },
    {
        survey_id: 4,
        title: "Market Trends",
        summary: "Analysis of market trends based on survey data.",
        data_type: "PAID",
        price: 70,
        buyer: null,
        sold_at: 0,
    },
    {
        survey_id: 5,
        title: "Customer Feedback",
        summary: "Aggregated customer feedback from surveys.",
        data_type: "FREE",
        price: 0,
        buyer: null,
        sold_at: 0,
    },
    {
        survey_id: 6,
        title: "Product Ratings",
        summary: "Ratings of products based on survey responses.",
        data_type: "PAID",
        price: 40,
        buyer: null,
        sold_at: 0,
    },
    {
        survey_id: 7,
        title: "Behavioral Insights",
        summary: "Behavioral patterns derived from survey data.",
        data_type: "PAID",
        price: 60,
        buyer: null,
        sold_at: 0,
    },
    {
        survey_id: 8,
        title: "Geographical Data",
        summary: "Geographical distribution of survey participants.",
        data_type: "FREE",
        price: 0,
        buyer: null,
        sold_at: 0,
    },
    {
        survey_id: 9,
        title: "Survey Trends",
        summary: "Trends observed in survey participation.",
        data_type: "PAID",
        price: 35,
        buyer: null,
        sold_at: 0,
    },
    {
        survey_id: 10,
        title: "Industry Insights",
        summary: "Survey data insights for specific industries.",
        data_type: "PAID",
        price: 80,
        buyer: null,
        sold_at: 0,
    },
    {
        survey_id: 11,
        title: "User Preferences",
        summary: "Data on user preferences from surveys.",
        data_type: "FREE",
        price: 0,
        buyer: null,
        sold_at: 0,
    },
    {
        survey_id: 12,
        title: "Spending Habits",
        summary: "Survey data on user spending habits.",
        data_type: "PAID",
        price: 55,
        buyer: null,
        sold_at: 0,
    },
    {
        survey_id: 13,
        title: "Feedback Analysis",
        summary: "Analysis of feedback collected from surveys.",
        data_type: "PAID",
        price: 45,
        buyer: null,
        sold_at: 0,
    },
    {
        survey_id: 14,
        title: "Engagement Metrics",
        summary: "Metrics on user engagement with surveys.",
        data_type: "FREE",
        price: 0,
        buyer: null,
        sold_at: 0,
    },
    {
        survey_id: 15,
        title: "Survey Response Times",
        summary: "Data on average response times for surveys.",
        data_type: "PAID",
        price: 25,
        buyer: null,
        sold_at: 0,
    },
    {
        survey_id: 16,
        title: "Customer Satisfaction",
        summary: "Survey data on customer satisfaction levels.",
        data_type: "PAID",
        price: 65,
        buyer: null,
        sold_at: 0,
    },
    {
        survey_id: 17,
        title: "Survey Participation Rates",
        summary: "Participation rates for various surveys.",
        data_type: "FREE",
        price: 0,
        buyer: null,
        sold_at: 0,
    },
    {
        survey_id: 18,
        title: "Market Analysis",
        summary: "Survey data for market analysis purposes.",
        data_type: "PAID",
        price: 75,
        buyer: null,
        sold_at: 0,
    },
    {
        survey_id: 19,
        title: "User Retention Data",
        summary: "Data on user retention based on surveys.",
        data_type: "PAID",
        price: 90,
        buyer: null,
        sold_at: 0,
    },
    {
        survey_id: 20,
        title: "Survey Effectiveness",
        summary: "Effectiveness of surveys in gathering data.",
        data_type: "FREE",
        price: 0,
        buyer: null,
        sold_at: 0,
    },
];



// Replace with your deployed program ID
export const PROGRAM_ID = new PublicKey("H79NApAAG8bSD9FSh1xAfSNppbsoCQS2vBP1M1dZNnG");
