

export const SurveyData = [
    {
        id: 1,
        title: " Ellipsis for Multiple Lines (Optional)  Ellipsis for Multiple Lines (Optional)1",
        reward: 10,
        duration: "2 days",
        limit: 100,
        participants: 50,
        status: "Active",
        owner_name: "John Doe",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",

    },
    {
        id: 2,
        title: " Ellipsis for Multiple Lines (Optional) 2",
        reward: 20,
        duration: "3 days",
        limit: 100,
        participants: 50,
        status: "Active",
        owner_name: "John Doe",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 3,
        title: " Ellipsis for Multiple Lines (Optional) 3",
        reward: 15,
        duration: "1 day",
        limit: 100,
        participants: 50,
        status: "Active",
        owner_name: "John Doe",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 4,
        title: "Survey 4",
        reward: 25,
        duration: "4 days",
        limit: 200,
        participants: 100,
        status: "Active",
        owner_name: "Jane Smith",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",    },
    {
        id: 5,
        title: "Survey 5",
        reward: 30,
        duration: "5 days",
        limit: 150,
        participants: 75,
        status: "inactive",
        owner_name: "Alice Johnson",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",    },
    {
        id: 6,
        title: "Survey 6",
        reward: 12,
        duration: "2 days",
        limit: 120,
        participants: 60,
        status: "active",
        owner_name: "Bob Brown",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 7,
        title: "Survey 7",
        reward: 18,
        duration: "3 days",
        limit: 130,
        participants: 65,
        status: "active",
        owner_name: "Charlie Davis",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 8,
        title: "Survey 8",
        reward: 22,
        duration: "4 days",
        limit: 140,
        participants: 70,
        status: "inactive",
        owner_name: "Diana Evans",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 9,
        title: "Survey 9",
        reward: 35,
        duration: "6 days",
        limit: 160,
        participants: 80,
        status: "active",
        owner_name: "Ethan Foster",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 10,
        title: "Survey 10",
        reward: 40,
        duration: "7 days",
        limit: 170,
        participants: 85,
        status: "active",
        owner_name: "Fiona Green",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 11,
        title: "Survey 11",
        reward: 28,
        duration: "5 days",
        limit: 180,
        participants: 90,
        status: "inactive",
        owner_name: "George Harris",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 12,
        title: "Survey 12",
        reward: 50,
        duration: "8 days",
        limit: 190,
        participants: 95,
        status: "active",
        owner_name: "Hannah Irving",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 13,
        title: "Survey 13",
        reward: 45,
        duration: "6 days",
        limit: 200,
        participants: 100,
        status: "active",
        owner_name: "Ian Jackson",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 14,
        title: "Survey 14",
        reward: 55,
        duration: "9 days",
        limit: 210,
        participants: 105,
        status: "inactive",
        owner_name: "Julia King",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 15,
        title: "Survey 15",
        reward: 60,
        duration: "10 days",
        limit: 220,
        participants: 110,
        status: "active",
        owner_name: "Kevin Lewis",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 16,
        title: "Survey 16",
        reward: 65,
        duration: "11 days",
        limit: 230,
        participants: 115,
        status: "active",
        owner_name: "Laura Martinez",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",    },
    {
        id: 17,
        title: "Survey 17",
        reward: 70,
        duration: "12 days",
        limit: 240,
        participants: 120,
        status: "inactive",
        owner_name: "Michael Nelson",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",    },
    {
        id: 18,
        title: "Survey 18",
        reward: 75,
        duration: "13 days",
        limit: 250,
        participants: 125,
        status: "active",
        owner_name: "Natalie Owens",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",    },
    {
        id: 19,
        title: "Survey 19",
        reward: 80,
        duration: "14 days",
        limit: 260,
        participants: 130,
        status: "active",
        owner_name: "Oliver Parker",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",    },
    {
        id: 20,
        title: "Survey 20",
        reward: 85,
        duration: "15 days",
        limit: 270,
        participants: 135,
        status: "inactive",
        owner_name: "Paula Quinn",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 21,
        title: "Survey 21",
        reward: 90,
        duration: "16 days",
        limit: 280,
        participants: 140,
        status: "active",
        owner_name: "Quincy Roberts",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 22,
        title: "Survey 22",
        reward: 95,
        duration: "17 days",
        limit: 290,
        participants: 145,
        status: "active",
        owner_name: "Rachel Scott",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    },
    {
        id: 23,
        title: "Survey 23",
        reward: 100,
        duration: "18 days",
        limit: 300,
        participants: 150,
        status: "inactive",
        owner_name: "Steven Turner",
        owner_avatar: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",    }
]